services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass $REDIS_PASSWORD --dir /data/ --appendonly yes
    ports:
      - "6379:6379"
    env_file: ../.env
    volumes:
      - ./data_redis:/data
  quirrel:
    image: ghcr.io/quirrel-dev/quirrel:main
    ports:
      - 9181:9181
    env_file: ../.env
